FINANCIAL_KEYWORDS = [
    "finansial", "keuangan", "saham", "investasi", "asuransi",
    "pinjaman", "kredit", "pajak", "dana", "uang",
    "mata uang", "obligasi", "ekuitas", "portofolio", "dividen",
    "modal", "manajemen keuangan", "inflasi", "likuiditas", "aset",
    "liabilitas", "arisan", "anggaran", "biaya", "pendapatan",
    "manajemen risiko", "pendanaan", "reksadana", "laba", "neraca",
    "kas", "investor", "debitur", "kreditur", "nilai tukar", "suku bunga",
    "hipotek", "tabungan", "investasi jangka panjang", "investasi jangka pendek",
    "dana pensiun", "rekening", "sistem pembayaran", "perbankan", "biaya transaksi",
    "komoditas", "derivatif", "keuangan pribadi", "keuangan korporasi", "spekulasi",
    "analisis fundamental", "analisis teknis", "trading", "manajemen portofolio", "laba rugi",
    "arbitrase", "diversifikasi", "strategi investasi", "margin", "ekonomi", 
    "perdagangan", "pasar modal", "kebijakan moneter", "kebijakan fiskal", "nilai intrinsik",
    "harga saham", "return on investment", "dampak ekonomi", "efisiensi pasar", "indikator ekonomi",
    "siklus ekonomi", "sistem perpajakan", "biaya modal", "kebijakan keuangan", "pialang",
    "spekulan", "asuransi kesehatan", "asuransi jiwa", "asuransi kendaraan", "asuransi properti",
    "asuransi perjalanan", "klaim asuransi", "uang tunai", "uang elektronik", "uang kertas",
    "uang logam", "uang digital", "uang kripto", "manajemen hutang", "manajemen piutang",
    "manajemen likuiditas", "manajemen risiko pasar", "manajemen risiko kredit", "manajemen risiko operasional"
]
