runtime: python39

entrypoint: gunicorn -w 2 -b :$PORT app.main:app

instance_class: F2

env_variables:
  ENV: "production"
  GOOGLE_CLOUD_PROJECT: "ents-h115"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
